import Link from 'next/link';
import { Cover } from '@/components/site/cover';
import { PageHeader } from '@/components/site/page-header';
import { JsonLd } from '@/components/site/json-ld';
import { TiltCard } from '@/components/site/tilt-card';
import { localePath, type Locale } from '@/lib/site-content';
import { getProjects } from '@/lib/public-content';
import { projectCopy, publicProjectSlugs } from '@/lib/project-copy';

const copy = { en: { label: 'Work', title: 'Things I have built and kept understandable', lede: 'Infrastructure, delivery pipelines, and platforms — each one connected to a real repository or an honest project state.' }, ar: { label: 'الأعمال', title: 'أعمال بنيتها وشرحتها بوضوح', lede: 'بنية تحتية وخطوط تسليم ومنصات — كل عمل مرتبط بمستودع حقيقي أو بحالة مشروع صريحة.' } } as const;

export async function PublicProjects({ locale }: { locale: Locale }) {
  const t = copy[locale];
  const projects = (await getProjects()).filter((project) => publicProjectSlugs().includes(project.slug));
  return <div className="page page-wide atlas-page" dir={locale === 'ar' ? 'rtl' : 'ltr'}><JsonLd data={{ '@context': 'https://schema.org', '@type': 'CollectionPage', name: t.title, description: t.lede, url: `https://ahmedekram.site${localePath(locale, '/projects')}`, inLanguage: locale === 'ar' ? 'ar-EG' : 'en-US', mainEntity: { '@type': 'ItemList', itemListElement: projects.map((project, index) => ({ '@type': 'ListItem', position: index + 1, name: projectCopy(locale, project.slug)?.title || project.title, url: `https://ahmedekram.site${localePath(locale, `/projects/${project.slug}`)}` })) } }} /><PageHeader label={t.label} title={t.title} lede={t.lede} /><div className="atlas-project-summary panel"><div><span className="label">{locale === 'ar' ? 'المشاريع' : 'Projects'}</span><strong>{projects.length}</strong><small>{locale === 'ar' ? 'مشاريع عامة' : 'public projects'}</small></div><div><span className="label">{locale === 'ar' ? 'التركيز' : 'Focus'}</span><strong>DevOps</strong><small>{locale === 'ar' ? 'من الفكرة إلى التشغيل' : 'idea to operation'}</small></div><div><span className="label">{locale === 'ar' ? 'الأدلة' : 'Evidence'}</span><strong>GitHub</strong><small>{locale === 'ar' ? 'مصادر قابلة للمراجعة' : 'inspectable sources'}</small></div></div>{projects.length === 0 ? <div className="panel px-8 py-20 text-center"><p className="text-muted-foreground">{locale === 'ar' ? 'لا توجد مشاريع الآن.' : 'No projects yet.'}</p></div> : <div className="atlas-project-grid">{projects.map((project, index) => { const details = projectCopy(locale, project.slug)!; return <TiltCard key={project.id} href={localePath(locale, `/projects/${project.slug}`)} className="panel atlas-project-card"><div className="atlas-project-top"><span className="atlas-project-role">{details.role}</span><span className={`status ${project.status === 'completed' ? 's-ok' : 's-warm'}`}>{project.status === 'completed' ? (locale === 'ar' ? 'مكتمل' : 'Completed') : (locale === 'ar' ? 'قيد التطوير' : 'In progress')}</span></div><div className="atlas-project-media"><Cover src={project.coverImage} alt={details.title} fallback={project.title.slice(0, 2).toUpperCase()} className="atlas-project-art" /></div><div className="atlas-project-body"><span className="atlas-index">PROJECT / {String(index + 1).padStart(2, '0')}</span><h2>{details.title}</h2><p className="atlas-project-copy">{details.result}</p><div className="atlas-tech-list">{details.stack.map((tech) => <span key={tech}>{tech}</span>)}</div><span className="atlas-project-open">{locale === 'ar' ? 'افتح دراسة الحالة' : 'Open case study'} <span aria-hidden>→</span></span></div></TiltCard>; })}</div>}</div>;
}
