import type { Locale } from './site-content';

export const UI: Record<Locale, {
  writing: string; work: string; about: string; contact: string; search: string; home: string;
  read: string; readWriting: string; allWriting: string; latestWriting: string; featuredWriting: string;
  startHere: string; topics: string; allTopics: string; minRead: string; share: string; copyLink: string; copied: string;
  backToWriting: string; articleNotFound: string; articleNotFoundLede: string;
  selectedWork: string; howIWork: string; proof: string; howICanHelp: string; aboutPreview: string; aboutPreviewBody: string;
  featured: string; viewWork: string; viewAllWork: string; talk: string; contactCta: string; contactBody: string;
  contactAsideTitle: string; contactAsideBody: string; contactAsideNote: string; messageForm: string; directChannel: string;
  messageSent: string; messageSentBody: string; sendMessage: string; sending: string; messageError: string;
  name: string; email: string; subject: string; message: string; directLinks: string; directLinksBody: string;
  emailUs: string; github: string; linkedin: string; errorTitle: string; errorBody: string; notFoundTitle: string; notFoundBody: string; goHome: string;
}> = {
  en: {
    writing: 'Writing', work: 'Work', about: 'About', contact: 'Contact', search: 'Search', home: 'Home', read: 'Read', readWriting: 'Read the writing', allWriting: 'All writing', latestWriting: 'Latest writing', featuredWriting: 'Featured writing', startHere: 'Start here', topics: 'Topics', allTopics: 'All topics', minRead: 'min read', share: 'Share', copyLink: 'Copy link', copied: 'Copied', backToWriting: 'Back to writing', articleNotFound: 'Article not found', articleNotFoundLede: 'The article you are looking for does not exist in this language.', selectedWork: 'Selected work', howIWork: 'How I work', proof: 'Proof', howICanHelp: 'How I can help', aboutPreview: 'A short introduction', aboutPreviewBody: 'I am a DevOps Engineer in Cairo. I care about dependable systems, useful automation, and explaining the decisions behind the work.', featured: 'Featured', viewWork: 'View the work', viewAllWork: 'View all work', talk: 'Start a conversation', contactCta: 'Send me the problem, not a job title', contactBody: 'Have a platform that needs to be more reliable, or a technical question you want to work through? Start with the context.', contactAsideTitle: 'Clear context beats a polished cover letter.', contactAsideBody: 'Share the symptom, the impact, and what you have already tried. A real constraint is the best place to begin.', contactAsideNote: 'A good message can be short. It only needs to be specific.', messageForm: 'Message form', directChannel: 'Direct channel', messageSent: 'Message sent', messageSentBody: 'Thank you. Your message reached the local contact flow.', sendMessage: 'Send message', sending: 'Sending…', messageError: 'Something went wrong. Try again, or email me directly.', name: 'Name', email: 'Email', subject: 'Subject', message: 'Message', directLinks: 'Direct links', directLinksBody: 'Prefer a direct route? Choose one below.', emailUs: 'Email', github: 'GitHub', linkedin: 'LinkedIn', errorTitle: 'Something went wrong', errorBody: 'An unexpected error occurred.', notFoundTitle: 'This page does not exist', notFoundBody: 'The address you followed is wrong, or the page has been moved.', goHome: 'Go home',
  },
  ar: {
    writing: 'الكتابة', work: 'الأعمال', about: 'عني', contact: 'تواصل', search: 'بحث', home: 'الرئيسية', read: 'اقرأ', readWriting: 'اقرأ الكتابة', allWriting: 'كل المقالات', latestWriting: 'أحدث الكتابة', featuredWriting: 'مقال مختار', startHere: 'ابدأ من هنا', topics: 'المواضيع', allTopics: 'كل المواضيع', minRead: 'دقيقة قراءة', share: 'مشاركة', copyLink: 'نسخ الرابط', copied: 'تم النسخ', backToWriting: 'العودة للكتابة', articleNotFound: 'المقال غير موجود', articleNotFoundLede: 'المقال الذي تبحث عنه غير متاح بهذه اللغة.', selectedWork: 'أعمال مختارة', howIWork: 'كيف أعمل', proof: 'دليل عملي', howICanHelp: 'كيف أساعد', aboutPreview: 'تعريف سريع', aboutPreviewBody: 'أنا مهندس DevOps في القاهرة. أهتم بالأنظمة الموثوقة والأتمتة المفيدة، وشرح القرارات التي تقف خلف العمل.', featured: 'مختار', viewWork: 'شاهد العمل', viewAllWork: 'شاهد كل الأعمال', talk: 'ابدأ محادثة', contactCta: 'أرسل المشكلة، وليس المسمى الوظيفي', contactBody: 'لديك منصة تحتاج إلى موثوقية أكثر، أو سؤال تقني تريد فهمه؟ ابدأ بالسياق.', contactAsideTitle: 'السياق الواضح أهم من رسالة توظيف مرتبة.', contactAsideBody: 'شارك العرض، والأثر، وما جربته بالفعل. القيد الحقيقي هو أفضل نقطة بداية.', contactAsideNote: 'الرسالة الجيدة يمكن أن تكون قصيرة. يكفي أن تكون محددة.', messageForm: 'نموذج الرسالة', directChannel: 'قناة مباشرة', messageSent: 'تم إرسال الرسالة', messageSentBody: 'شكرًا لك. وصلت رسالتك إلى تدفق التواصل المحلي.', sendMessage: 'إرسال الرسالة', sending: 'جارٍ الإرسال…', messageError: 'حدث خطأ. حاول مرة أخرى، أو راسلني مباشرة.', name: 'الاسم', email: 'البريد الإلكتروني', subject: 'الموضوع', message: 'الرسالة', directLinks: 'روابط مباشرة', directLinksBody: 'تفضل التواصل مباشرة؟ اختر رابطًا بالأسفل.', emailUs: 'البريد', github: 'GitHub', linkedin: 'LinkedIn', errorTitle: 'حدث خطأ ما', errorBody: 'وقع خطأ غير متوقع.', notFoundTitle: 'هذه الصفحة غير موجودة', notFoundBody: 'العنوان الذي اتبعته غير صحيح، أو تم نقل الصفحة.', goHome: 'العودة للرئيسية',
  },
};

export function isLocale(value: string): value is Locale {
  return value === 'en' || value === 'ar';
}
